lua/neotest-jest/init.lua
The current ID generation includes the quotes that surround the test description, but it expects them to be double quotes. This changes the ID generation to exclude the quotations so it doesn't matter if the test uses single or double quotes.
=> fix: generate correct test ids when using single quoted strings

lua/neotest-jest/init.lua
**PR #11** 
Add escaping chars in jest command option --testNamePattern=<regex>. Now we can run single test cointaing special char in test name.
**Before**
**After**
=> Escape test name pattern in jest command

lua/neotest-jest/init.lua
This should make it work with https://github.com/mxsdev/nvim-dap-vscode-js
It doesn't always seem to work (see discussion in https://github.com/mxsdev/nvim-dap-vscode-js/issues/2) but highly likely the problem doesn't lie in this PR nor in nvim-dap-vscode-js...
=> Add debugging support

lua/neotest-jest/init.lua
The main fix is setting the `cwd` to the adapter root. This fixes the case where I'm at the root directory `project/` but I have my frontend code in a subdirectory `project/frontend/`.
I also put a small fix and a cleanup refactor in this PR. Can remove them and put up a separate PR if you prefer.
=> Run jest command from the adapter root

README.md, lua/neotest-jest/init.lua, tests/init_options_spec.lua
Hi 👋 
It would be great if the neotest-jest plugin honoured `env` args passed as adapter config and run spec config, merging the 2 together by default. Hopefully this accomplishes that!
Thanks
=> Support defining env arguments for adapters

README.md, lua/neotest-jest/init.lua
Fixes #29 
Puts the `cwd` spec field behind a configuration option.
=> fix: put cwd behind a config option

lua/neotest-jest/init.lua
Removing quotes results in the pattern generated not matching the test if the test name contains quotes.
Fixes #33
=> don't remove quotes from test names

lua/neotest-jest/init.lua
Neotest core has switched to custom file finding, which requires specifying custom filtering. This prevents node_modules being searched for tests
=> feat: filter_dir function

.github/workflows/workflow.yaml, README.md, lua/neotest-jest/init.lua, lua/neotest-jest/util.lua
Hello!
This PR allows to pass `--watch` flag and streaming test results. 
The solution is heavily inspired by `neotest-python` code ([link](https://github.com/nvim-neotest/neotest-python/blob/master/lua/neotest-python/init.lua#L160))
I think it Closes: https://github.com/haydenmeade/neotest-jest/issues/43
Note: for now when the tests are being rerun the icon on the summary window is not updated due to: https://github.com/nvim-neotest/neotest/issues/169
How to use:
In your setup add flag to `jestCommand` option:
```lua
require("neotest").setup({
adapters = {
require("neotest-jest")({
jestCommand = "jest --watch ",
}),
},
}
```
Demo:
https://user-images.githubusercontent.com/35625949/209707959-51967539-3539-4875-ac37-b2e0da85e6f0.mov
TODO:
[x] allow to run tests with `--watch` flag
[x] add …
=> Add support for `--watch` flag

lua/neotest-jest/util.lua, tests/init_options_spec.lua, tests/init_spec.lua
Just some small changes to adapt to the new async library in neotest.
Depends on nvim-neotest/neotest#228
=> feat: new async library

README.md
Not sure if this is needed or not but for a little while I thought I had a broken config. Turns out somehow I only had the typescript language parser installed and neotest-jest did not work repeatedly telling be there were no available tests. This might be helpful to explicitly call out for others in future.
=> Add instructions for Treesitter parsers

README.md, lua/neotest-jest/init.lua
This PR adds back support for monorepos by detecting a jest dependency at the root level of the repo.
Added some docs for some example configuration to handle edge cases like different jest configs per package or if your monorepo test runner does not support running an individual test file
I'm not sure this is the right solution, especially since I did this to work for me, but thoughts are welcome
=> detect root level package json jest dependency

README.md
The repository is now on on neotest organization
=> docs: remove repository transfer statement

lua/neotest-jest/init.lua, spec/array.test.ts, spec/basic.test.ts, spec/nestedDescribe.test.ts, tests/init_spec.lua
The current position discovery query only searches for test/contexts that use arrow function for their body, but Jest allows you to use both arrow functions and normal functions. This PR updates the query to support both kinds
=> Add support for tests declared with normal functions

lua/neotest-jest/init.lua
default behaviour if no jest dependency is found is to use jest adapter
closes #70
=> fix: don't load adapter if root project does not have jest dependency

lua/neotest-jest/init.lua
Some codebases use different suffixes to distinguish between types of tests.
Examples:
- `test.integration.ts`
- `test.regression.ts`
- `test.unit.ts`
=> Support new test file name suffixes: unit, regression and integration

README.md, lua/neotest-jest/init.lua, lua/neotest-jest/jest-util.lua, lua/neotest-jest/parameterized-tests.lua, spec/parameterized.test.ts, tests/init_spec.lua
Hey!
This is a PR that allows to see and run parameterized tests in the summary window.
The main algorithm here is:
1. Run the treesitter queries on the test file.
2. If the file do not have any parameterized tests (it.each, test.each etc.) do not do anything special just return normal test positions
3. If file contains parameterized tests then:
- run `jest` to discover every test in the file
- find all of the test results from `jest` that are on the same position returned by treesitter
- add new positions to the position returned by a treesitter
Closes: https://github.com/haydenmeade/neotest-jest/issues/2
How to run:
Checkout `neotest-jest` to my branch
Demo:
https://user-images.githubusercontent.com/35625949/209713822-dc550b5b-0690-4011-935f-6b4895ab1e17.mov
TODO:
=> Adds support for parameterized tests

README.md
This new command uses the exact same command the plugin uses by default to find the jest binary. It ensures it'll always work the same.
Ideally, a new `watch = true` could be used, making it transparent to the user. If you like this idea I can work on the implementation.
=> Update README `watch` mode instructions

lua/neotest-jest/init.lua, tests/init_spec.lua
Got a quick fix here for `watch` mode. Should fix #43 
README states that we should be able to set the `jestCommand` like so: `lua require('neotest').run.run({ jestCommand = 'jest --watch ' })`
That arg is not being referenced anywhere, and should act as an override to any more global defined `jestCommand`.
The change here is to just use the `arg.jestCommand` if it exists.
This got watch mode working for me
=> Use args.jestCommand if exists as an override

LICENSE.md
Add an MIT license, which is the license used by other repos in this org.
Resolves #88
=> docs: add LICENSE.md

lua/neotest-jest/init.lua
Added "e2e-spec" prefix to the list of valid tests prefixes.
=> Consider .e2e-spec. prefix as a test file

lua/neotest-jest/init.lua
This plugin in windows has 2 issues:
1) Jest only accepts paths with forward slash but the plugin sends it backwards as reported in #42
~~2) After solving the first issue i noticed that neotest doesn't update the sign for each test making every test appear with an X even if the test passed. This is caused due to the test having an id like `c:\\path\file::test_name` and the Jest output reports the path like `C:\\path\file::test_name` (notice the capital drive)~~  It seems that neotest now respects the case of the test id so this is no longer an issue.
This PR attemps to solve both issues.
First issue was solved using ` vim.fs.normalize` as recommended in https://github.com/nvim-neotest/neotest-jest/pull/44#issuecomment-1420417168.
~~Second issue was solved adding a windows only validation …
=> fix windows support

lua/neotest-jest/init.lua
BREAKING_CHANGE: switch to the new (function_expression) pattern that replaces the previous (function). This will be a breaking change for anyone on v0.9.1 or earlier of treesitter
This addresses the failures in test discovery as reported in https://github.com/nvim-neotest/neotest-jest/issues/99
=> fix: fix javascript treesitter queries

.github/workflows/workflow.yaml, README.md, tests/init_spec.lua
* Updated styling so stylua passes.
* I've changed the workflow to use neovim 0.9.0 instead of 0.7.0 due to the neotest requiring at least neovim 0.9.0 after version 4. See the explanation [here](https://github.com/adrigzr/neotest-mocha/pull/13#issuecomment-1917015899) for more information.
=> Fix styling, update workflow

README.md
Monorepo configuration in Readme is not working when I tried to run the tests from the Neotest summary window. This is because `vim.fn.expand('%:p')` returns Neotest's summary window path instead of the test file path when I try to invoke `run` from the summary window. 
The changes in the PR pick up the test file path from the `neotest.RunArgs`
=> Fix monorepo configuration in readme

lua/neotest-jest/init.lua
Updates the file path parsing to escape special characters. This fixes #108
=> fix: escape test file path

lua/neotest-jest/init.lua
adds another check to see if jest should be used to test.
For some repositories the jest dependency is not in the nearest package.json (relative to the test file) nor in the root of the project. In this case the former approach would return `No tests found`
But imo if we have the package.json test script set to jest it indicates that we want to use jest for testing.
This might also solve the issue #74
=> Enhance jest detection

lua/neotest-jest/init.lua, spec/basic.test.ts, tests/adapter_discover_positions_spec.lua
=> feat: add support for call expressions in a test case
